# Generated by Django 3.2.7 on 2021-10-14 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('setup_place', models.CharField(max_length=50, verbose_name='설치 장소')),
                ('setup_day', models.CharField(help_text='설치 날짜를 입력하시오, YYYY/MM/DD hh:mm:ss', max_length=19, verbose_name='설치 날짜')),
                ('company_name', models.CharField(help_text='업체명을 입력하시오', max_length=100, verbose_name='업체명')),
                ('display', models.CharField(help_text='해상도를 입력하시오, NxM', max_length=9, verbose_name='해상도')),
                ('max_brgt', models.IntegerField(default=0, verbose_name='최대 밝기')),
                ('player_serial', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='플레이어 Serial')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('login_fail_count', models.IntegerField(default=0)),
                ('login_time', models.CharField(default=0, help_text='hh:mm:ss', max_length=50)),
                ('var_user_id', models.CharField(max_length=50, verbose_name='user_id')),
                ('var_picture_index', models.IntegerField(default=-1, verbose_name='picture_index')),
                ('var_text_index', models.IntegerField(blank=True, default=-1, verbose_name='text_index')),
                ('var_check_index', models.IntegerField(default=2, verbose_name='check_index')),
                ('var_move_movie_index', models.IntegerField(default=-1, verbose_name='move_movie_index')),
                ('var_sun', models.IntegerField(default=-1, verbose_name='sun')),
                ('var_mon', models.IntegerField(default=-1, verbose_name='mon')),
                ('var_tues', models.IntegerField(default=-1, verbose_name='tues')),
                ('var_wed', models.IntegerField(default=-1, verbose_name='wed')),
                ('var_thurs', models.IntegerField(default=-1, verbose_name='thurs')),
                ('var_fri', models.IntegerField(default=-1, verbose_name='fri')),
                ('var_sat', models.IntegerField(default=-1, verbose_name='sat')),
                ('var_pattern_now', models.IntegerField(default=-1, verbose_name='pattern_now')),
                ('var_my', models.IntegerField(default=2, verbose_name='my')),
                ('var_bright_check', models.IntegerField(default=36, verbose_name='bright_check')),
                ('var_CDS_check', models.IntegerField(default=0, verbose_name='CDS_check')),
                ('var_auto_bright_max_check', models.IntegerField(default=-1, verbose_name='auto_bright_max_check')),
                ('var_auto_bright_min_check', models.IntegerField(default=-1, verbose_name='auto_bright_min_check')),
                ('var_auto_CDS_max_check', models.IntegerField(default=-1, verbose_name='auto_CDS_max_check')),
                ('var_auto_CDS_min_check', models.IntegerField(default=-1, verbose_name='auto_CDS_min_check')),
                ('var_auto_on_hour_check', models.IntegerField(default=-1, verbose_name='auto_on_hour_check')),
                ('var_auto_on_min_check', models.IntegerField(default=-1, verbose_name='auto_on_min_check')),
                ('var_auto_off_hour_check', models.IntegerField(default=-1, verbose_name='auto_off_hour_check')),
                ('var_auto_off_min_check', models.IntegerField(default=-1, verbose_name='auto_off_min_check')),
                ('var_first_loading', models.IntegerField(default=1, verbose_name='first_loading')),
                ('var_brightness_mode', models.IntegerField(default=-1, verbose_name='brightness_mode')),
                ('var_powermode', models.IntegerField(default=-1, verbose_name='powermode')),
                ('var_manualcontrol', models.IntegerField(default=-1, verbose_name='manualcontrol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
